name: Slack notification

on:
  workflow_call:
    inputs:
      tests-result:
        required: true
        type: string
        description: "Test run status"
      environment:
        type: string
        description: "Environment: localhost / marcinkapturski.com"
        required: true
    secrets:
      SLACK_WEBHOOK:
        required: true

jobs:
  report:
    name: Report results on Slack
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout the repository
        if: always()
        uses: actions/checkout@v3

      - name: Install Node.js
        if: always()
        uses: actions/setup-node@v3
        with:
          node-version: ">=16.0.0"

      - name: Workflow run url
        run: echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        shell: bash

      - name: install dependency
        if: always()
        run: |
          yarn add isomorphic-fetch

      - name: Slack (${{ inputs.tests-result }}) notification
        if: always()
        run: |
          export SCRIPT_PATH=${{ github.workspace }}/cypress/slack/${{ inputs.tests-result == 'success' && 'success_message.js' || 'failed_message.js'}}
          export EVENT_NAME=${{ github.event_name }}
          export ENVIRONMENT=${{ inputs.environment }}
          export BRANCH_NAME=${GITHUB_REF#refs/heads/}
          export RUN_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          yarn node $SCRIPT_PATH "${{ secrets.SLACK_WEBHOOK }}" "$EVENT_NAME" "$BRANCH_NAME" "$RUN_URL" "$ENVIRONMENT"
